# Generated by Django 4.1.5 on 2023-01-13 20:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='id_client',
        ),
        migrations.RemoveField(
            model_name='user',
            name='photo',
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('48c946e0-557f-4a94-81f1-74f813d2c0e6'), primary_key=True, serialize=False, verbose_name='id'),
        ),
    ]
