# Generated by Django 4.1.5 on 2023-01-13 20:37

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MainClients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=25, verbose_name='Имя')),
                ('last_name', models.CharField(blank=True, max_length=25, verbose_name='Фамилия')),
                ('city', models.CharField(blank=True, max_length=20, verbose_name='Город')),
                ('photo', models.ImageField(blank=True, upload_to='photo/clients/', verbose_name='Фото')),
                ('born_date', models.DateField(blank=True, verbose_name='Дата рождения')),
                ('born_time', models.TimeField(blank=True, null=True, verbose_name='Время рождения')),
                ('date_created', models.DateTimeField(default=datetime.datetime.now, verbose_name='Дата добавления')),
                ('telephone', models.CharField(blank=True, max_length=15, verbose_name='Телефон')),
                ('viber', models.BooleanField(default=False, verbose_name='Viber')),
                ('whatsup', models.BooleanField(default=False, verbose_name='Whatsup')),
                ('telegram', models.CharField(blank=True, max_length=50, verbose_name='Telegram')),
                ('instagram', models.CharField(blank=True, max_length=50, verbose_name='Instagram')),
                ('vk', models.CharField(blank=True, max_length=50, verbose_name='ВК')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
    ]
