# Generated by Django 4.1.5 on 2023-05-02 21:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workplaceapp', '0004_services_alter_mainclients_date_created_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Services',
        ),
        migrations.AlterField(
            model_name='mainclients',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 3, 0, 33, 36, 176280), verbose_name='Дата добавления'),
        ),
    ]
