# Generated by Django 4.1.5 on 2023-05-12 07:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workplaceapp', '0006_alter_mainclients_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainclients',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 12, 10, 8, 29, 20095), verbose_name='Дата добавления'),
        ),
    ]
