# Generated by Django 4.1.5 on 2023-05-13 17:10

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_rename_lenght_time_services_length_time_and_more'),
        ('workplaceapp', '0007_alter_mainclients_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainclients',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 13, 20, 10, 10, 478639), verbose_name='Дата добавления'),
        ),
        migrations.CreateModel(
            name='ServiceClients',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('date', models.DateTimeField(default=datetime.datetime(2023, 5, 13, 20, 10, 10, 479639), verbose_name='Дата')),
                ('comment', models.TextField(verbose_name='Комментарий')),
                ('client', models.ManyToManyField(to='workplaceapp.mainclients', verbose_name='Клиент')),
                ('service', models.ManyToManyField(to='mainapp.services', verbose_name='Услуга')),
            ],
            options={
                'verbose_name': 'Оказанная услуга',
                'verbose_name_plural': 'Оказанные услуги',
            },
        ),
    ]
