# Generated by Django 4.1.5 on 2023-05-13 17:21

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workplaceapp', '0008_alter_mainclients_date_created_serviceclients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainclients',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 13, 20, 21, 7, 891241), verbose_name='Дата добавления'),
        ),
        migrations.RemoveField(
            model_name='serviceclients',
            name='client',
        ),
        migrations.AlterField(
            model_name='serviceclients',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата'),
        ),
        migrations.AddField(
            model_name='serviceclients',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='workplaceapp.mainclients', verbose_name='Клиент'),
        ),
    ]
