# Generated by Django 4.1.5 on 2023-05-13 18:05

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_rename_lenght_time_services_length_time_and_more'),
        ('workplaceapp', '0009_alter_mainclients_date_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainclients',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 13, 21, 5, 49, 917644), verbose_name='Дата добавления'),
        ),
        migrations.RemoveField(
            model_name='serviceclients',
            name='service',
        ),
        migrations.AddField(
            model_name='serviceclients',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.services', verbose_name='Услуга'),
        ),
    ]
