# Generated by Django 4.1.5 on 2023-05-14 08:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workplaceapp', '0010_alter_mainclients_date_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainclients',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 14, 11, 53, 34, 319424), verbose_name='Дата добавления'),
        ),
        migrations.AlterField(
            model_name='serviceclients',
            name='comment',
            field=models.TextField(blank=True, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='serviceclients',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 5, 14, 11, 53, 34, 319424), verbose_name='Дата'),
        ),
    ]
