# Generated by Django 4.1.5 on 2023-06-12 16:59

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_rename_lenght_time_services_length_time_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workplaceapp', '0011_alter_mainclients_date_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainclients',
            name='born_date',
            field=models.DateField(verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='mainclients',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 12, 19, 59, 37, 464091), verbose_name='Дата добавления'),
        ),
        migrations.AlterField(
            model_name='mainclients',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='serviceclients',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_of', to='workplaceapp.mainclients', verbose_name='Клиент'),
        ),
        migrations.AlterField(
            model_name='serviceclients',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 6, 12, 19, 59, 37, 466091), verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='serviceclients',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_of', to='mainapp.services', verbose_name='Услуга'),
        ),
    ]
