# Generated by Django 4.1.5 on 2023-07-22 16:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workplaceapp', '0012_alter_mainclients_born_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceclients',
            name='price',
            field=models.IntegerField(blank=True, null=True, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='mainclients',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 22, 19, 52, 33, 101824), verbose_name='Дата добавления'),
        ),
        migrations.AlterField(
            model_name='serviceclients',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 7, 22, 19, 52, 33, 101824), verbose_name='Дата'),
        ),
    ]
