# Generated by Django 4.1.5 on 2023-01-12 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
                ('deleted', models.BooleanField(default=False, verbose_name='Удалено')),
                ('title', models.CharField(max_length=256, verbose_name='Заголовок')),
                ('preamble', models.CharField(max_length=256, verbose_name='Вступление')),
                ('body', models.TextField(verbose_name='Содержание')),
                ('body_as_markdown', models.BooleanField(default=False, verbose_name='Разметка')),
                ('image', models.ImageField(blank=True, upload_to='images/news/', verbose_name='Картинка')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
            },
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
                ('deleted', models.BooleanField(default=False, verbose_name='Удалено')),
                ('title', models.CharField(max_length=256, verbose_name='Заголовок')),
                ('preamble', models.CharField(max_length=256, verbose_name='Вступление')),
                ('body', models.TextField(verbose_name='Описание')),
                ('body_as_markdown', models.BooleanField(default=False, verbose_name='Разметка')),
                ('image', models.ImageField(blank=True, upload_to='photo/services/', verbose_name='Картинка')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='Стоимость')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
            },
        ),
    ]
