# Generated by Django 4.1.5 on 2023-05-12 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_alter_news_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormatService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of', models.CharField(max_length=100, verbose_name='Формат')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Формат консультации',
                'verbose_name_plural': 'Форматы консультаций',
            },
        ),
        migrations.AlterModelOptions(
            name='services',
            options={'ordering': ('pk',), 'verbose_name': 'Услуга', 'verbose_name_plural': 'Услуги'},
        ),
        migrations.AddField(
            model_name='services',
            name='lenght_time',
            field=models.CharField(max_length=256, null=True, verbose_name='Продолжительность'),
        ),
    ]
