# Generated by Django 4.1.5 on 2023-05-12 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_formatservice_alter_services_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='formats',
            field=models.ManyToManyField(to='mainapp.formatservice'),
        ),
    ]
